manifest:
  remotes:
    - name: nrfconnect
      url-base: https://github.com/nrfconnect
  projects:
    - name: nrf
      repo-path: sdk-nrf
      remote: nrfconnect
      revision: v1.7.1
      import: true
    # Drivers repository
    - name: max30102
      path: max
      revision: 763ebe2c64390af0ffa9054e54f6dbbcc5d78b27
      url: https://github.com/tinkhauser/max30102_zephyr
      import: true
  self:
    # This repository should be cloned to 
    path: max30102-demo
